ion_device_src += $(addprefix ion/src/device/n0100/drivers/, \
  board.cpp \
  led.cpp \
  power.cpp \
  reset.cpp \
)

ion_device_src += $(addprefix ion/src/device/shared/, \
  dummy/archive.cpp \
)

LDSCRIPT ?= ion/src/device/n0100/flash.ld
